### all pelanggan
GET http://localhost:10002/v1/allpelanggan
Accept: application/json

### pelanggan ada di database
POST http://localhost:10002/v1/pelanggan
Content-Type: application/json

{"nolanggan" : "01007231"}

### pelanggan tidak ada di database
POST http://localhost:10002/v1/pelanggan
Content-Type: application/json

{"nolanggan" : "01007230"}